### ISSUE TITLE
500 Application Error

### ISSUE THREAD

**Issue by xHomu** [manawiki/starrail#174]
1. Go to Mana.wiki 
2. Click on mana.wiki/starrail 
3. Click on the Yukong link

![image](https://github.com/manawiki/starrail/assets/84349818/66ea54eb-8a42-4ab2-b5df-f9bd2fc299e7)

![image](https://github.com/manawiki/starrail/assets/84349818/e9e95d88-b7e2-4989-98bc-d12d5e39ede3)

403 route errors, my best guess is something went wrong with the crossite cookies. 

@pogseal any ideas? I haven't pushed any changes I plan on making to the cookie sessions yet, so that shouldn't be it.

**Comment by pogseal** [comment]
Missed calling a field to check for the site type, the next push should fix.

```
reloadDocument={site.type == "custom" && true}
```

**Comment by xHomu** [comment]
@pogseal Yeah, I suspect the problem was when the client's entry to the site is the new home page, cause the cookies to not set right.

I was seeing some weird samesite warnings too, probably related.

**Comment by xHomu** [comment]
End up being a samesite cors bug, resolved https://github.com/manawiki/core/commit/ddf23de3f9d94e1d7bf296c889118aa15faae5ec#diff-18627e43f563ac1c21bb3e8f2f5c1368fbc04a311fc5ac59a681071b539417ad
